[package]
name = "arrayvec"
version = "0.3.14"
authors = ["bluss"]
license = "MIT/Apache-2.0"

description = "A vector with a fixed capacity, it can be stored on the stack too. Implements fixed capacity ArrayVec and ArrayString."
documentation = "http://bluss.github.io/arrayvec"
repository = "https://github.com/bluss/arrayvec"

keywords = ["stack", "vector", "array", "data-structure", "no_std"]

[dependencies.odds]
version = "0.2.12"
default-features = false

[dependencies.nodrop]
version = "0.1.6"
path = "nodrop"
default-features = false

[features]
default = ["std"]
std = ["odds/std", "nodrop/std"]
